version: "3"
services:
  app:
    build: .
    image: share-post:1.0
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - APP_DEFAULT_URL_HOST=localhost
      - APP_DEFAULT_URL_PORT=3000
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./containers/mysql:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 4306:3306

volumes:
  bundle:
  mysql:
