# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8mb4
  charaset: utf8mb4
  host: <%= Rails.application.credentials.db[:database_host] %>
  username: <%= Rails.application.credentials.db[:database_user] %>
  password: <%= Rails.application.credentials.db[:database_password] %>
  database: <%= ENV['DB_DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default
  database: "share_post_test"

production:
  <<: *default
